"""initial_schema

Revision ID: ce73f2a0432d
Revises: 
Create Date: 2026-06-14 14:57:04.146601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce73f2a0432d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.String(length=255), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('target_metric', sa.JSON(), nullable=False),
    sa.Column('autonomy_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('best_metric_value', sa.String(length=100), nullable=True),
    sa.Column('current_plan', sa.JSON(), nullable=True),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('subprocess_pid', sa.Integer(), nullable=True),
    sa.Column('last_checkpoint_path', sa.Text(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_experiment_id'), 'metrics', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_metrics_mission_id'), 'metrics', ['mission_id'], unique=False)
    op.create_table('model_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.String(length=255), nullable=True),
    sa.Column('weights_path', sa.Text(), nullable=True),
    sa.Column('checkpoint_path', sa.Text(), nullable=True),
    sa.Column('best_metric_name', sa.String(length=100), nullable=True),
    sa.Column('best_metric_value', sa.Float(), nullable=True),
    sa.Column('is_champion', sa.Boolean(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_records_experiment_id'), 'model_records', ['experiment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_records_experiment_id'), table_name='model_records')
    op.drop_table('model_records')
    op.drop_index(op.f('ix_metrics_mission_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_experiment_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_table('missions')
    op.drop_table('experiments')
    # ### end Alembic commands ###
