"""add_approval_gates

Revision ID: d8199b5e6752
Revises: ce73f2a0432d
Create Date: 2026-06-14 15:47:39.174253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8199b5e6752'
down_revision: Union[str, Sequence[str], None] = 'ce73f2a0432d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_gates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('gate_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_gates_mission_id'), 'approval_gates', ['mission_id'], unique=False)
    op.create_index(op.f('ix_approval_gates_status'), 'approval_gates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_gates_status'), table_name='approval_gates')
    op.drop_index(op.f('ix_approval_gates_mission_id'), table_name='approval_gates')
    op.drop_table('approval_gates')
    # ### end Alembic commands ###
